# Generated by Django 2.0 on 2017-12-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutDataForm',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('key', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('workout_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
            ],
        ),
    ]
